"""M02-M04 runtime foundation for CPSWM."""

from .identity_time_frames import (
    ClockAlignment,
    FrameRegistry,
    FrameTransform,
    IdentityNamespace,
    IdentityRegistry,
    Quaternion,
    ScopedIdentity,
    TimeAlignmentRegistry,
    Vector3,
    normalize_utc,
)
from .persistence_replay import (
    AppendOnlyTransactionLog,
    ExecutionMode,
    ReplayManifest,
    SnapshotCatalog,
    StoreCatalog,
    StorePartition,
    TransactionLogDump,
)
from .runtime_orchestration import (
    HandlerOutput,
    InProcessRuntime,
    MessageKind,
    ReplayRunner,
    RuntimeMessage,
    RuntimeMessageRecord,
    VersionBundle,
    build_replay_manifest,
    build_version_bundle,
    compare_replay_runs,
)

__all__ = [
    "AppendOnlyTransactionLog",
    "ClockAlignment",
    "ExecutionMode",
    "FrameRegistry",
    "FrameTransform",
    "HandlerOutput",
    "IdentityNamespace",
    "IdentityRegistry",
    "InProcessRuntime",
    "MessageKind",
    "Quaternion",
    "ReplayManifest",
    "ReplayRunner",
    "RuntimeMessage",
    "RuntimeMessageRecord",
    "ScopedIdentity",
    "SnapshotCatalog",
    "StoreCatalog",
    "StorePartition",
    "TimeAlignmentRegistry",
    "TransactionLogDump",
    "Vector3",
    "VersionBundle",
    "build_replay_manifest",
    "build_version_bundle",
    "compare_replay_runs",
    "normalize_utc",
]
