"""Train-only rendered-instance affinity probe on externally pinned public proposals.

The existing detector outputs are reused, not regenerated by this experiment.
Private masks supervise train pairs and later evaluate fixed development outputs;
they never select public pixels, feature vectors, proposals or inference pairs.
"""

from __future__ import annotations

import argparse
import io
import json
import shutil
import tempfile
from collections import Counter
from pathlib import Path

import numpy as np
from diagnose_offline_frontend import (
    digest,
    inventory,
    require,
    source_identity,
    verify_historical_collection,
)
from instance_affinity_dataset import label_frame, public_frame
from verify_offline_factor_capture import _json, _public

from cpswm.data_preflight.instance_affinity import checkpoint_sha256, fit, predict, restore
from cpswm.system.reproducibility import canonical_json, content_sha256

ROOT = Path(__file__).resolve().parents[1]
METHODS = ("fasterrcnn", "ssdlite")


def verify_frontends(directory, *, ledger_pin, source, input_inventory, capture_config):
    """Use the caller's original ledger pin, never an output's self-signed hash."""
    require(not directory.is_symlink(), "symlink frontend directory")
    ledger = directory / "case-results.json"
    require(not ledger.is_symlink() and digest(ledger) == ledger_pin, "frontend ledger pin differs")
    cases = _json(ledger)
    require(
        type(cases) is list
        and [(c["phase"], c["detector"]) for c in cases]
        == [(p, m) for p in ("run", "verify") for m in METHODS]
        and all(type(c["exit_code"]) is int and c["exit_code"] == 0 for c in cases)
        and len({c["source_sha"] for c in cases}) == 1,
        "frontend ledger is not the complete successful paired run and replay",
    )
    expected_source = source_identity(source)
    result, pins = {}, {}
    for method in METHODS:
        folder = directory / method
        actual = inventory(folder)
        require(
            set(actual) == {"public.json", "report.json", "inputs.json"}, "frontend files differ"
        )
        require(
            all(c["output_sha256"] == actual for c in cases if c["detector"] == method),
            "frontend bytes differ from pinned replay ledger",
        )
        report = _json(folder / "report.json")
        public = _json(folder / "public.json")
        require(
            report["detector_kind"] == method
            and report["diagnostic_source_files"] == expected_source
            and report["capture_source_files"] == capture_config["source_files"]
            and report["collection_inventory_sha256"] == input_inventory["inventory.json"]
            and _json(folder / "inputs.json") == input_inventory
            and report["public_predictions_sha256"] == content_sha256(public),
            "frontend source or collection binding differs",
        )
        require(len(public) == len(report["frames"]) == 96, "frontend omits fixed frames")
        require(
            [(f["house_index"], f["sdk_index"], f["split"]) for f in report["frames"]]
            == [
                (h, t, "train" if h <= 8 else "validation")
                for h in range(1, 13)
                for t in range(4, 12)
            ],
            "frontend frame partition or order differs",
        )
        require(
            all(
                f["action_id"] == p["command"]["action_id"]
                for f, p in zip(report["frames"], public, strict=True)
            ),
            "frontend frame owner differs",
        )
        result[method], pins[method] = public, actual
    require(
        [p["command"] for p in result[METHODS[0]]] == [p["command"] for p in result[METHODS[1]]],
        "frontend commands are not paired",
    )
    return result, dict(ledger_sha256=ledger_pin, files=pins, source_files=expected_source)


def private_labels(directory, record, audit):
    index, offset = record["house_index"], record["sdk_index"]
    private = directory / f"house-{index:02d}/unity-logs/evaluator_only"
    # Scheduling/label/prediction metadata is not part of the public sensor contract.
    public = {
        k: v
        for k, v in record.items()
        if k not in {"house_index", "sdk_index", "split", "labels", "predictions"}
    }
    with np.load(private / f"instances/{offset:03d}-masks.npz", allow_pickle=False) as masks:
        return label_frame(
            public,
            _json(private / f"sdk-events/{offset:03d}.json"),
            _json(private / f"instances/{offset:03d}.json"),
            masks,
            np.load(private / f"instances/{offset:03d}-segmentation.npy", allow_pickle=False),
            [r for r in audit["instances"] if r["house_index"] == index],
            sdk_rgb_bytes=(private / f"sdk-events/{offset:03d}-rgb.npy").read_bytes(),
            sdk_depth_bytes=(private / f"sdk-events/{offset:03d}-depth.npy").read_bytes(),
        )


def scores(targets, predictions):
    y = np.asarray(targets)
    p = np.asarray([np.nan if v is None else v for v in predictions], dtype=np.float64)
    require(y.shape == p.shape and np.isin(y, (-1, 0, 1)).all(), "invalid scoring arrays")
    selected = y != -1
    require(np.isfinite(p[selected]).all(), "labelled pair has no public prediction")
    require(((p[selected] >= 0) & (p[selected] <= 1)).all(), "invalid affinity score")
    if not selected.any():
        return dict(pairs=0, bce=None, brier=None)
    y, p = y[selected].astype(float), p[selected]
    q = np.clip(p, 1e-12, 1 - 1e-12)
    return dict(
        pairs=len(y),
        bce=float(-(y * np.log(q) + (1 - y) * np.log1p(-q)).mean()),
        brier=float(np.square(p - y).mean()),
    )


def summarize(records, prevalence):
    targets = np.concatenate([r["labels"]["targets"] for r in records])
    predictions = [p for r in records for p in r["predictions"]]
    valid = np.concatenate([r["valid"] for r in records])
    reasons = Counter()
    for r in records:
        reasons.update(r["labels"]["void_reasons"])
    return dict(
        frames=len(records),
        zero_candidate_frames=sum(not r["candidates"] for r in records),
        raw_candidate_pairs=sum(len(c["pair_indices"]) for r in records for c in r["candidates"]),
        unique_pairs=len(targets),
        public_valid_pairs=int(valid.sum()),
        positive_pairs=int((targets == 1).sum()),
        negative_pairs=int((targets == 0).sum()),
        void_pairs=int((targets == -1).sum()),
        void_reasons=dict(reasons),
        model=scores(targets, predictions),
        training_frequency_constant=scores(targets, [prevalence if v else None for v in valid]),
    )


def array_bytes(value):
    stream = io.BytesIO()
    np.save(stream, value, allow_pickle=False)
    return stream.getvalue()


def encoded(value):
    return (canonical_json(value) + "\n").encode()


def build(directory, frontends, *, input_inventory, frontend_binding):
    before_source = source_identity(ROOT)
    records = []
    for index in range(1, 13):
        house = directory / f"house-{index:02d}"
        capture = _json(house / "capture.json")
        raw, _ = _public(house / "public", capture["provenance"])
        require(len(raw) == 8, "fixed house must retain eight frames")
        for local, (command, delivery, _) in enumerate(raw):
            ordinal = (index - 1) * 8 + local
            record = public_frame(command, delivery, {m: frontends[m][ordinal] for m in METHODS})
            record.update(
                house_index=index,
                sdk_index=local + 4,
                split="train" if index <= 8 else "validation",
            )
            records.append(record)
    require(len({r["action_id"] for r in records}) == 96, "duplicate public action")
    print(json.dumps(dict(phase="public_pairs", frames=len(records))), flush=True)
    audit = _json(directory / "runtime-partition-audit.json")
    training = [r for r in records if r["split"] == "train"]
    for record in training:
        record["labels"] = private_labels(directory, record, audit)
    features = np.concatenate([r["X"] for r in training])
    targets = np.concatenate([r["labels"]["targets"] for r in training])
    model = fit(features, targets, partition="train")
    model_pin = checkpoint_sha256(model)
    restored = restore(json.loads(encoded(model)), model_pin)
    for record in records:
        record["predictions"] = predict(restored, record["X"], record["valid"])
        require(
            record["predictions"] == predict(model, record["X"], record["valid"]),
            "restored model changed predictions",
        )
    print(json.dumps(dict(phase="fit_and_public_predict", frames=len(records))), flush=True)
    for record in records:
        if record["split"] == "validation":
            record["labels"] = private_labels(directory, record, audit)
    by_house = {
        str(h): summarize([r for r in records if r["house_index"] == h], model["prevalence"])
        for h in range(1, 13)
    }
    by_split = {
        s: summarize([r for r in records if r["split"] == s], model["prevalence"])
        for s in ("train", "validation")
    }
    for split, value in by_split.items():
        houses = [by_house[str(h)] for h in range(1, 13) if (h <= 8) == (split == "train")]
        observed = [h for h in houses if h["model"]["pairs"] > 0]
        value["houses_with_supervision"] = len(observed)
        value["house_macro"] = {
            m: {
                k: float(np.mean([h[m][k] for h in observed])) if observed else None
                for k in ("bce", "brier")
            }
            for m in ("model", "training_frequency_constant")
        }
    artifacts = {"model.json": encoded(model)}
    frames = []
    for ordinal, record in enumerate(records):
        prefix = f"frames/{ordinal:03d}"
        arrays = dict(
            features=record["X"],
            pairs=record["pairs"],
            valid=record["valid"],
            targets=record["labels"]["targets"],
            scores=np.asarray(
                [np.nan if p is None else p for p in record["predictions"]], dtype=np.float64
            ),
        )
        for name, array in arrays.items():
            artifacts[f"{prefix}/{name}.npy"] = array_bytes(array)
        artifacts[f"{prefix}/public.json"] = encoded(
            dict(metadata=record["public_metadata"], candidates=record["candidates"])
        )
        artifacts[f"{prefix}/supervision.json"] = encoded(
            {
                k: v.tolist() if isinstance(v, np.ndarray) else v
                for k, v in record["labels"].items()
                if k != "targets"
            }
        )
        frames.append(
            dict(
                prefix=prefix,
                house_index=record["house_index"],
                split=record["split"],
                action_id=record["action_id"],
                sdk_index=record["sdk_index"],
                summary=summarize([record], model["prevalence"]),
            )
        )
    require(
        inventory(directory) == input_inventory, "collection changed during affinity experiment"
    )
    require(source_identity(ROOT) == before_source, "source changed during affinity experiment")
    import hashlib

    report = dict(
        scope="RENDERED_INSTANCE_AFFINITY_DEVELOPMENT_BASELINE",
        source_files=before_source,
        collection_inventory_sha256=input_inventory["inventory.json"],
        frontend_binding=frontend_binding,
        detector_inference_reused=True,
        training_performed=True,
        calibration_performed=False,
        world_instance_identity_assigned=False,
        observation_likelihood_written=False,
        online_memory_write=False,
        full_mask_predicted=False,
        formal_position_reference_selected=False,
        independent_acceptance=False,
        model_sha256=model_pin,
        frames=frames,
        by_house=by_house,
        by_split=by_split,
        overall=summarize(records, model["prevalence"]),
        members={name: hashlib.sha256(raw).hexdigest() for name, raw in artifacts.items()},
        interpretation=(
            "Scores concern rendered instance membership on fixed public pairs, not calibrated "
            "likelihood, physical depth ownership, complete masks, cross-view identity or task "
            "benefit. Validation is previously exposed development data."
        ),
    )
    artifacts["report.json"] = encoded(report)
    return artifacts


def save_or_verify(output, artifacts, *, verify):
    import hashlib

    expected = {name: hashlib.sha256(raw).hexdigest() for name, raw in artifacts.items()}
    if verify:
        require(inventory(output) == expected, "fresh trained outputs differ")
        return
    require(not output.exists() and not output.is_symlink(), "refuse to overwrite experiment")
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(tempfile.mkdtemp(prefix=output.name + "-", dir=output.parent))
    try:
        for name, raw in artifacts.items():
            path = temporary / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(raw)
        require(inventory(temporary) == expected, "output write differs")
        temporary.rename(output)
    finally:
        if temporary.exists():
            shutil.rmtree(temporary)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in (
        "collection",
        "capture-source",
        "archive",
        "sdk-python",
        "binary",
        "frontends",
        "frontend-source",
        "output",
    ):
        parser.add_argument("--" + name, type=Path, required=True)
    parser.add_argument("--inventory-sha256", required=True)
    parser.add_argument("--frontend-ledger-sha256", required=True)
    parser.add_argument("--verify", action="store_true")
    args = parser.parse_args()
    require(not args.output.is_symlink(), "symlink output")
    directory, output = args.collection.resolve(), args.output.resolve()
    for source in (
        directory,
        args.frontends.resolve(),
        args.capture_source.resolve(),
        args.frontend_source.resolve(),
        ROOT,
    ):
        require(
            not output.is_relative_to(source) and not source.is_relative_to(output),
            "inputs and output must be disjoint",
        )
    require(args.verify or not output.exists(), "refuse to overwrite experiment")
    before, config = verify_historical_collection(
        directory,
        pin=args.inventory_sha256,
        capture_source=args.capture_source.resolve(),
        archive=args.archive.resolve(),
        sdk_python=args.sdk_python.absolute(),
        binary=args.binary.resolve(),
    )
    frontends, binding = verify_frontends(
        args.frontends,
        ledger_pin=args.frontend_ledger_sha256,
        source=args.frontend_source,
        input_inventory=before,
        capture_config=config,
    )
    artifacts = build(directory, frontends, input_inventory=before, frontend_binding=binding)
    _, after = verify_frontends(
        args.frontends,
        ledger_pin=args.frontend_ledger_sha256,
        source=args.frontend_source,
        input_inventory=before,
        capture_config=config,
    )
    require(
        content_sha256(after) == content_sha256(binding),
        "frontend inputs changed during experiment",
    )
    save_or_verify(output, artifacts, verify=args.verify)
    print(
        json.dumps(
            dict(complete=True, frames=96, training_performed=True, natural_factor_completed=False)
        )
    )


if __name__ == "__main__":
    main()
