"""Public project-two LLM/VLM evidence adapter surface."""

from cpswm.contracts.llm_roles import LLMProviderIdentity

from .adapter import (
    CalibratedLikelihoodBundle,
    CandidateProposalBundle,
    CandidateProposalItem,
    DeterministicEvidenceProvider,
    LLMEvidenceAdapter,
    LLMEvidenceAdapterResult,
    LLMEvidenceCache,
    LLMEvidenceProvider,
    LocalModelEvidenceProvider,
    OpenAICompatibleEvidenceProvider,
    ProviderHTTPResponse,
    ReferencedPosteriorBundle,
    UrllibLLMHTTPTransport,
)
from .contracts import (
    LLMCacheStatus,
    LLMCalibrationReceipt,
    LLMCallAuditReceipt,
    LLMCandidateKind,
    LLMEvidenceCapability,
    LLMEvidenceOutput,
    LLMEvidenceRequest,
    LLMFusionPermission,
    LLMGeneratedCandidate,
    LLMInvocationAccounting,
    LLMProbabilitySemantics,
    TruthLeakageError,
)

__all__ = [
    "CalibratedLikelihoodBundle",
    "CandidateProposalBundle",
    "CandidateProposalItem",
    "DeterministicEvidenceProvider",
    "LLMCacheStatus",
    "LLMCalibrationReceipt",
    "LLMCallAuditReceipt",
    "LLMCandidateKind",
    "LLMEvidenceAdapter",
    "LLMEvidenceAdapterResult",
    "LLMEvidenceCache",
    "LLMEvidenceCapability",
    "LLMEvidenceOutput",
    "LLMEvidenceProvider",
    "LLMEvidenceRequest",
    "LLMFusionPermission",
    "LLMGeneratedCandidate",
    "LLMInvocationAccounting",
    "LLMProbabilitySemantics",
    "LLMProviderIdentity",
    "LocalModelEvidenceProvider",
    "OpenAICompatibleEvidenceProvider",
    "ProviderHTTPResponse",
    "ReferencedPosteriorBundle",
    "TruthLeakageError",
    "UrllibLLMHTTPTransport",
]
